ci:
    config:
        schema_version: 1
        trunk_branch: main
        triggers:
            - src/**
        cli_version: v0.16.5-rc.1
        cli_version_sha: 148cf877cf7f78f0a66fd6407e9c5e06e601c858
        tag_grammar:
            prefix: rel-
        state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
        manifest_file: .github/manifest.yaml
        manifest_key: ci
        builds:
            - name: lib
              workflow: .github/workflows/build-lib.yaml
              triggers: []
        changelog:
            contributors: true
    state:
        release:
            sha: f78a3eaea20f3631e8eecb995ca14445e46ba83c
            version: rel-0.1.0
            committed_at: "2026-07-19T15:10:58Z"
            committed_by: github-actions[bot]
    latest_release:
        version: rel-0.1.0
        sha: f78a3eaea20f3631e8eecb995ca14445e46ba83c
        released_on: "2026-07-19T15:10:58Z"
        released_by: github-actions[bot]
