ci:
    config:
        schema_version: 1
        trunk_branch: main
        triggers:
            - src/**
        cli_version: v0.16.2-rc.0
        cli_version_sha: c35b673ce5ea01782e8d3fd7a6244469f3b9b93f
        tag_grammar:
            prefix: rel-
        state_token: ${{ secrets.CASCADE_STATE_TOKEN }}
        manifest_file: .github/manifest.yaml
        manifest_key: ci
        builds:
            - name: lib
              workflow: .github/workflows/build-lib.yaml
              triggers: []
        changelog:
            contributors: true
    state:
        release:
            sha: b82192f18ecfd8f4d937aff3f2d2f367abbe7d5d
            version: rel-0.1.0
            committed_at: "2026-07-16T09:07:46Z"
            committed_by: github-actions[bot]
    latest_release:
        version: rel-0.1.0
        sha: b82192f18ecfd8f4d937aff3f2d2f367abbe7d5d
        released_on: "2026-07-16T09:07:46Z"
        released_by: github-actions[bot]
